# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Brightcove Integrations Support Documentation
email: training@brightcove.com
description: |- # this means to ignore newlines until "baseurl:"
  Brightcove is proud to offer a suite of integrations to meet you where you work.  These integrations allow you to manage your video publishing workflow and harness the power of video.
# baseurl: "" # the subpath of your site, e.g. /blog
site_url: "https://integrations.support.brightcove.com"
site_domain: "integrations.support.brightcove.com"

# Build settings
# theme: minima

# local server (for "jekyll serve") will be localhost:{PORT number below}
port: 8500

product: Video Cloud CMS Connectors
color: rgb(51, 51, 51)
product_color: rgb(239, 108, 42)
product_icon: "COVE004_Brightcove_Video_Cloud_Logo_RGB_K.svg"
search_id: "017969773216783359937:gqomuefz6aq"
feedbackify_id: "15079"
bing_custom_config_id: "bcf990db-c43d-40f3-9d30-616b2374b8f0"
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
# plugins
plugins:
  - jekyll-last-modified-at

# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
